/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type LinkPageSingleton = {
  _id: string;
  _type: "linkPageSingleton";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  links?: Array<{
    _key: string;
  } & LinkPageItem>;
};

export type HomepageSingleton = {
  _id: string;
  _type: "homepageSingleton";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
  artworks?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "imageItem";
    _key: string;
  } | {
    _key: string;
  } & VideoItem>;
};

export type Download = {
  _type: "download";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
  };
  media?: unknown;
  title?: string;
  description?: string;
};

export type Address = {
  _type: "address";
  name?: string;
  street?: string;
  city?: string;
  postcode?: string;
  country?: string;
};

export type LinkPageItem = {
  _type: "linkPageItem";
  title?: string;
  url?: string;
  newTab?: boolean;
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }>;
};

export type LinkItem = {
  _type: "linkItem";
  url?: string;
  title?: string;
};

export type BlockContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
  listItem?: "bullet";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
} | {
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  caption?: string;
  alt?: string;
  _type: "image";
  _key: string;
}>;

export type Dimensions = {
  _type: "dimensions";
  width?: string;
  height?: string;
  depth?: string;
  units?: "mm" | "cm" | "m";
};

export type VideoItem = {
  _type: "videoItem";
  url?: string;
  caption?: string;
};

export type ImageItem = {
  _type: "imageItem";
  asset?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
  };
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  caption?: string;
  alt?: string;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  answer?: BlockContent;
  order?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes = LinkPageSingleton | HomepageSingleton | Download | Address | LinkPageItem | LinkItem | BlockContent | Dimensions | VideoItem | ImageItem | Faq | SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityImageHotspot | SanityImageCrop | SanityFileAsset | SanityImageAsset | SanityImageMetadata | Geopoint | Slug | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/sanity/lib/queries.ts
// Variable: REDIRECTS_QUERY
// Query: *[_type == "redirect"]{  _id, short, destination, description}
export type REDIRECTS_QUERYResult = Array<never>;
// Variable: REDIRECT_QUERY
// Query: *[_type == "artwork" && short == $slug][0]{  _id, short, slug}
export type REDIRECT_QUERYResult = null;
// Variable: FAQS_QUERY
// Query: *[_type == "faq"] | order(order asc){  _id,  question,  answer,  order}
export type FAQS_QUERYResult = Array<{
  _id: string;
  question: string | null;
  answer: BlockContent | null;
  order: number | null;
}>;
// Variable: ARTWORKS_QUERY
// Query: *[_type == "artwork"] | order(dateTime(publishedAt) desc){  _id,   title,   slug,  publishedAt,  artworkDate,  priority,  major,  categories[]->{    _id,    title  },  mainImage{    asset->{      _id,      _ref,      url,      metadata    },  },  description,  briefDescription,}
export type ARTWORKS_QUERYResult = Array<never>;
// Variable: ARTWORK_QUERY
// Query: *[_type == "artwork" && slug.current == $slug][0]{  _id,  title,  slug,  shortTitle,  publishedAt,  artworkDate,  mainImage{    asset->{      _id,      _ref,      url,      metadata    },  },  artworks[] {    ...,    asset->{      _id,      _ref,      url,      metadata    },  },  categories[]->{    _id,    title  },  material,  dimensions {    width,    height,    depth,    units  },  description[] {    ...,    _type == "image" => {      ...,      asset->{        _id,        _ref,        url,        metadata {          dimensions {            width,            height,            aspectRatio          },          lqip,          blurHash,          hasAlpha,          isOpaque,          palette        }      }    }  },  links[] {    title,    url  },  downloads[] {    asset->{      _id,      url    }  },  "relatedArtworks": relatedArtworks[].artwork->{    _id,    title,    slug,    shortTitle,    artworkDate,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },  },  "relatedBiography": relatedBiography[].biography->{    _id,    title,    slug,    shortTitle,    startDate,    endDate,    type,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },  },}
export type ARTWORK_QUERYResult = null;
// Variable: BIOGRAPHY_QUERY
// Query: *[_type == "biography" && slug.current == $slug][0]{  _id,  title,  slug,  shortTitle,  startDate,  endDate,  type,  mainImage{    asset->{      _id,      _ref,      url,      metadata    },  },  artworks[] {    ...,    asset->{      _id,      _ref,      url,      metadata    },  },  address,  description[] {    ...,    _type == "image" => {      ...,      asset->{        _id,        _ref,        url,        metadata {          dimensions {            width,            height,            aspectRatio          },          lqip,          blurHash,          hasAlpha,          isOpaque,          palette        }      }    }  },  "relatedArtworks": relatedArtworks[].artwork->{    _id,    title,    slug,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },  },  "relatedBiography": relatedBiography[].biography->{    _id,    title,    slug,    type,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },  },  categories[]->{    _id,    title  },  links[] {    title,    url  },  downloads[] {    asset->{      _id,      url    }  }}
export type BIOGRAPHY_QUERYResult = null;
// Variable: BIOGRAPHIES_QUERY
// Query: *[_type == "biography"] | order(dateTime(startDate) desc){    _id,    title,    startDate,    endDate,    slug,    description,    type,    address,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },}
export type BIOGRAPHIES_QUERYResult = Array<never>;
// Variable: CURRENT_BIOGRAPHIES_QUERY
// Query: *[_type == "biography" && (type == "group" || type == "solo") && startDate <= now() && endDate >= now()] | order(dateTime(startDate) asc){    _id,    title,    startDate,    endDate,    slug,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },}
export type CURRENT_BIOGRAPHIES_QUERYResult = Array<never>;
// Variable: UPCOMING_BIOGRAPHIES_QUERY
// Query: *[_type == "biography" && (type == "group" || type == "solo") && startDate > now()] | order(dateTime(startDate) asc){    _id,    title,    startDate,    endDate,    slug,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },}
export type UPCOMING_BIOGRAPHIES_QUERYResult = Array<never>;
// Variable: ALL_SHOWS_QUERY
// Query: *[_type == "biography" && (type == "group" || type == "solo")] | order(dateTime(startDate) asc){    _id,    title,    startDate,    endDate,    slug,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },}
export type ALL_SHOWS_QUERYResult = Array<never>;
// Variable: HOMEPAGE_QUERY
// Query: *[_type == "homepageSingleton"][0]{  _id,  title,  description,  artworks[] {    _type,    _type == "imageItem" => {      asset->{        _id,        _ref,        url,        metadata      },      alt,      caption    },    _type == "videoItem" => {      asset->{        _id,        _ref,        url      },      alt,      caption    }  },   artworkReference->{    _id,    title,    slug,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },  },}
export type HOMEPAGE_QUERYResult = {
  _id: string;
  title: string | null;
  description: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "normal";
    listItem?: "bullet";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  } | {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    caption?: string;
    alt?: string;
    _type: "image";
    _key: string;
  }> | null;
  artworks: Array<{
    _type: "imageItem";
    asset: {
      _id: string;
      _ref: null;
      url: string | null;
      metadata: SanityImageMetadata | null;
    } | null;
    alt: string | null;
    caption: string | null;
  } | {
    _type: "videoItem";
    asset: null;
    alt: null;
    caption: string | null;
  }> | null;
  artworkReference: null;
} | null;
// Variable: STUDIOS_QUERY
// Query: *[_type == "studio"] | order(dateTime(publishedAt) desc){  _id,   title,   slug,  publishedAt,  categories[]->{    _id,    title  },  mainImage{    asset->{      _id,      _ref,      url,      metadata    },  },  description,}
export type STUDIOS_QUERYResult = Array<never>;
// Variable: STUDIO_QUERY
// Query: *[_type == "studio" && slug.current == $slug][0]{  _id,   title,   slug,  publishedAt,  mainImage{    asset->{      _id,      _ref,      url,      metadata    },  },  media[] {    ...,    asset->{      _id,      _ref,      url,      metadata    },  },  description[] {    ...,    _type == "block" => {      ...,      markDefs[]{        ...,        _type == "link" => {          href,          _type        }      }    },    _type == "image" => {      ...,      asset->{        _id,        _ref,        url,        metadata {          dimensions {            width,            height,            aspectRatio          },          lqip,          blurHash,          hasAlpha,          isOpaque,          palette        }      }    },    _type == "artworkReference" => {      ...,      artwork->{        _id,        title,        slug,        artworkDate,        mainImage{          asset->{            _id,            _ref,            url,            metadata          }        }      }    }  },  "relatedArtworks": relatedArtworks[].artwork->{    _id,    title,    slug,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },  },  "relatedBiography": relatedBiography[].biography->{    _id,    title,    slug,    type,    mainImage{      asset->{        _id,        _ref,        url,        metadata      }    },  },  categories[]->{    _id,    title  },  links[] {    title,    url  },  downloads[] {    asset->{      _id,      url    }  }}
export type STUDIO_QUERYResult = null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "*[_type == \"redirect\"]{\n  _id, short, destination, description\n}": REDIRECTS_QUERYResult;
    "*[_type == \"artwork\" && short == $slug][0]{\n  _id, short, slug\n}": REDIRECT_QUERYResult;
    "*[_type == \"faq\"] | order(order asc){\n  _id,\n  question,\n  answer,\n  order\n}": FAQS_QUERYResult;
    "*[_type == \"artwork\"] | order(dateTime(publishedAt) desc){\n  _id, \n  title, \n  slug,\n  publishedAt,\n  artworkDate,\n  priority,\n  major,\n  categories[]->{\n    _id,\n    title\n  },\n  mainImage{\n    asset->{\n      _id,\n      _ref,\n      url,\n      metadata\n    },\n  },\n  description,\n  briefDescription,\n}": ARTWORKS_QUERYResult;
    "*[_type == \"artwork\" && slug.current == $slug][0]{\n  _id,\n  title,\n  slug,\n  shortTitle,\n  publishedAt,\n  artworkDate,\n  mainImage{\n    asset->{\n      _id,\n      _ref,\n      url,\n      metadata\n    },\n  },\n  artworks[] {\n    ...,\n    asset->{\n      _id,\n      _ref,\n      url,\n      metadata\n    },\n  },\n  categories[]->{\n    _id,\n    title\n  },\n  material,\n  dimensions {\n    width,\n    height,\n    depth,\n    units\n  },\n  description[] {\n    ...,\n    _type == \"image\" => {\n      ...,\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          },\n          lqip,\n          blurHash,\n          hasAlpha,\n          isOpaque,\n          palette\n        }\n      }\n    }\n  },\n\n  links[] {\n    title,\n    url\n  },\n  downloads[] {\n    asset->{\n      _id,\n      url\n    }\n  },\n  \"relatedArtworks\": relatedArtworks[].artwork->{\n    _id,\n    title,\n    slug,\n    shortTitle,\n    artworkDate,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n  },\n  \"relatedBiography\": relatedBiography[].biography->{\n    _id,\n    title,\n    slug,\n    shortTitle,\n    startDate,\n    endDate,\n    type,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n  },\n}": ARTWORK_QUERYResult;
    "*[_type == \"biography\" && slug.current == $slug][0]{\n  _id,\n  title,\n  slug,\n  shortTitle,\n  startDate,\n  endDate,\n  type,\n  mainImage{\n    asset->{\n      _id,\n      _ref,\n      url,\n      metadata\n    },\n  },\n  artworks[] {\n    ...,\n    asset->{\n      _id,\n      _ref,\n      url,\n      metadata\n    },\n  },\n  address,\n  description[] {\n    ...,\n    _type == \"image\" => {\n      ...,\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          },\n          lqip,\n          blurHash,\n          hasAlpha,\n          isOpaque,\n          palette\n        }\n      }\n    }\n  },\n  \"relatedArtworks\": relatedArtworks[].artwork->{\n    _id,\n    title,\n    slug,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n  },\n  \"relatedBiography\": relatedBiography[].biography->{\n    _id,\n    title,\n    slug,\n    type,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n  },\n  categories[]->{\n    _id,\n    title\n  },\n  links[] {\n    title,\n    url\n  },\n  downloads[] {\n    asset->{\n      _id,\n      url\n    }\n  }\n}": BIOGRAPHY_QUERYResult;
    "*[_type == \"biography\"] | order(dateTime(startDate) desc){\n    _id,\n    title,\n    startDate,\n    endDate,\n    slug,\n    description,\n    type,\n    address,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n}": BIOGRAPHIES_QUERYResult;
    "*[_type == \"biography\" && (type == \"group\" || type == \"solo\") && startDate <= now() && endDate >= now()] | order(dateTime(startDate) asc){\n    _id,\n    title,\n    startDate,\n    endDate,\n    slug,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n}": CURRENT_BIOGRAPHIES_QUERYResult;
    "*[_type == \"biography\" && (type == \"group\" || type == \"solo\") && startDate > now()] | order(dateTime(startDate) asc){\n    _id,\n    title,\n    startDate,\n    endDate,\n    slug,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n}": UPCOMING_BIOGRAPHIES_QUERYResult;
    "*[_type == \"biography\" && (type == \"group\" || type == \"solo\")] | order(dateTime(startDate) asc){\n    _id,\n    title,\n    startDate,\n    endDate,\n    slug,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n}": ALL_SHOWS_QUERYResult;
    "*[_type == \"homepageSingleton\"][0]{\n  _id,\n  title,\n  description,\n  artworks[] {\n    _type,\n    _type == \"imageItem\" => {\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      },\n      alt,\n      caption\n    },\n    _type == \"videoItem\" => {\n      asset->{\n        _id,\n        _ref,\n        url\n      },\n      alt,\n      caption\n    }\n  },\n   artworkReference->{\n    _id,\n    title,\n    slug,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n  },\n}": HOMEPAGE_QUERYResult;
    "*[_type == \"studio\"] | order(dateTime(publishedAt) desc){\n  _id, \n  title, \n  slug,\n  publishedAt,\n  categories[]->{\n    _id,\n    title\n  },\n  mainImage{\n    asset->{\n      _id,\n      _ref,\n      url,\n      metadata\n    },\n  },\n  description,\n}": STUDIOS_QUERYResult;
    "*[_type == \"studio\" && slug.current == $slug][0]{\n  _id, \n  title, \n  slug,\n  publishedAt,\n  mainImage{\n    asset->{\n      _id,\n      _ref,\n      url,\n      metadata\n    },\n  },\n  media[] {\n    ...,\n    asset->{\n      _id,\n      _ref,\n      url,\n      metadata\n    },\n  },\n  description[] {\n    ...,\n    _type == \"block\" => {\n      ...,\n      markDefs[]{\n        ...,\n        _type == \"link\" => {\n          href,\n          _type\n        }\n      }\n    },\n    _type == \"image\" => {\n      ...,\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata {\n          dimensions {\n            width,\n            height,\n            aspectRatio\n          },\n          lqip,\n          blurHash,\n          hasAlpha,\n          isOpaque,\n          palette\n        }\n      }\n    },\n    _type == \"artworkReference\" => {\n      ...,\n      artwork->{\n        _id,\n        title,\n        slug,\n        artworkDate,\n        mainImage{\n          asset->{\n            _id,\n            _ref,\n            url,\n            metadata\n          }\n        }\n      }\n    }\n  },\n  \"relatedArtworks\": relatedArtworks[].artwork->{\n    _id,\n    title,\n    slug,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n  },\n  \"relatedBiography\": relatedBiography[].biography->{\n    _id,\n    title,\n    slug,\n    type,\n    mainImage{\n      asset->{\n        _id,\n        _ref,\n        url,\n        metadata\n      }\n    },\n  },\n  categories[]->{\n    _id,\n    title\n  },\n  links[] {\n    title,\n    url\n  },\n  downloads[] {\n    asset->{\n      _id,\n      url\n    }\n  }\n}": STUDIO_QUERYResult;
  }
}
